"""Canonical archive, feature-search, and search-orchestration APIs.

Archive state, candidate-search strategies, and high-level orchestration live
in this package.
"""

from .archive import (
    ACTIVE_SET_FORMAT_IDENTIFIER,
    ACTIVE_SET_FORMAT_VERSION,
    ARCHIVE_PROXY_OBJECTIVES,
    DEFAULT_ACTIVE_CORRELATION_THRESHOLD,
    DEFAULT_ARCHIVE_CORRELATION_THRESHOLD,
    DEFAULT_ARCHIVE_QUALITY_THRESHOLD,
    DEFAULT_FIRST_PROMOTION_TOP_K,
    DEFAULT_PROMOTION_ADD_K,
    DEFAULT_PROMOTION_INTERVAL,
    DEFAULT_PROMOTION_MEAN_GAIN,
    DEFAULT_PROMOTION_MIN_GAIN,
    DEFAULT_PROMOTION_REFRESH_TOP_N,
    FORMAT_IDENTIFIER,
    FORMAT_VERSION,
    OBJECTIVES_PER_ARCHIVE,
    SNAPSHOT_FORMAT_IDENTIFIER,
    SNAPSHOT_FORMAT_VERSION,
    SNAPSHOT_MAPPING_REFERENCE,
    ActiveSetManager,
    ActiveSetSnapshot,
    ArchiveSnapshot,
    ArchiveStep,
    GPArchiveStep,
    absolute_pearson_correlation,
    build_snapshot_document,
    correlation_rejection,
    decode_expression,
    encode_expression,
    is_correlated_pairwise,
    load_active_set_snapshot,
    load_archive,
    load_snapshot,
    validate_archive_quality_threshold,
    validate_correlation_threshold,
    write_snapshot,
)
from .enumerative_search import (
    BoundedExpressionEnumerator,
    BoundedGrammarEnumerator,
    EnumerationResult,
    build_enumerative_search,
    collect_evaluation_free_expressions,
    collect_unique_expressions,
    iter_bounded_expressions,
)
from .gp import MaterializingGeneticProgramming, build_search_algorithm
from .random_search import build_random_search
from .search import (
    ARCHIVE_MINIMIZE,
    DEFAULT_MAX_DEPTH,
    ArchiveProgressTracker,
    CandidateEvaluator,
    CandidateGenerator,
    MaterializingArchiveSearch,
    canonical_expression_key,
)
from .unbound_enumerative_search import (
    UnboundEnumerativeSearch,
    build_unbound_enumerative_search,
)
from .runner import (
    DIAGNOSTIC_COLUMNS,
    RunnerDiagnosticsRecorder,
    SearchRunResult,
    SearchStrategy,
    run_feature_search,
    write_summary_json,
)

__all__ = [
    "ACTIVE_SET_FORMAT_IDENTIFIER",
    "ACTIVE_SET_FORMAT_VERSION",
    "ARCHIVE_MINIMIZE",
    "ARCHIVE_PROXY_OBJECTIVES",
    "DEFAULT_ACTIVE_CORRELATION_THRESHOLD",
    "DEFAULT_ARCHIVE_CORRELATION_THRESHOLD",
    "DEFAULT_ARCHIVE_QUALITY_THRESHOLD",
    "DEFAULT_FIRST_PROMOTION_TOP_K",
    "DEFAULT_MAX_DEPTH",
    "DEFAULT_PROMOTION_ADD_K",
    "DEFAULT_PROMOTION_INTERVAL",
    "DEFAULT_PROMOTION_MEAN_GAIN",
    "DEFAULT_PROMOTION_MIN_GAIN",
    "DEFAULT_PROMOTION_REFRESH_TOP_N",
    "DIAGNOSTIC_COLUMNS",
    "FORMAT_IDENTIFIER",
    "FORMAT_VERSION",
    "OBJECTIVES_PER_ARCHIVE",
    "SNAPSHOT_FORMAT_IDENTIFIER",
    "SNAPSHOT_FORMAT_VERSION",
    "SNAPSHOT_MAPPING_REFERENCE",
    "ArchiveProgressTracker",
    "ArchiveSnapshot",
    "ArchiveStep",
    "ActiveSetManager",
    "ActiveSetSnapshot",
    "BoundedExpressionEnumerator",
    "BoundedGrammarEnumerator",
    "CandidateEvaluator",
    "CandidateGenerator",
    "EnumerationResult",
    "GPArchiveStep",
    "MaterializingArchiveSearch",
    "MaterializingGeneticProgramming",
    "RunnerDiagnosticsRecorder",
    "SearchRunResult",
    "SearchStrategy",
    "UnboundEnumerativeSearch",
    "absolute_pearson_correlation",
    "build_enumerative_search",
    "build_random_search",
    "build_search_algorithm",
    "build_snapshot_document",
    "build_unbound_enumerative_search",
    "canonical_expression_key",
    "collect_evaluation_free_expressions",
    "collect_unique_expressions",
    "correlation_rejection",
    "decode_expression",
    "encode_expression",
    "is_correlated_pairwise",
    "iter_bounded_expressions",
    "load_active_set_snapshot",
    "load_archive",
    "load_snapshot",
    "run_feature_search",
    "validate_archive_quality_threshold",
    "validate_correlation_threshold",
    "write_snapshot",
    "write_summary_json",
]
