"""Feature-search strategies and their shared evaluated-search lifecycle."""

from ..archive import (
    DEFAULT_ACTIVE_CORRELATION_THRESHOLD,
    DEFAULT_FIRST_PROMOTION_TOP_K,
    DEFAULT_PROMOTION_ADD_K,
    DEFAULT_PROMOTION_INTERVAL,
    DEFAULT_PROMOTION_MEAN_GAIN,
    DEFAULT_PROMOTION_MIN_GAIN,
    DEFAULT_PROMOTION_REFRESH_TOP_N,
    FilteredArchiveStep,
    FilteredHistoryArchive,
    GPArchiveStep,
    absolute_pearson_correlation,
    correlation_rejection,
    is_correlated_pairwise,
    validate_archive_quality_threshold,
    validate_correlation_threshold,
)
from .enumerative_search import (
    BoundedExpressionEnumerator,
    BoundedGrammarEnumerator,
    EnumerationResult,
    build_enumerative_search,
    collect_evaluation_free_expressions,
    collect_unique_expressions,
    iter_bounded_expressions,
)
from .gp import MaterializingGeneticProgramming, build_search_algorithm
from .random_search import build_random_search
from .search import (
    ARCHIVE_MINIMIZE,
    DEFAULT_MAX_DEPTH,
    ArchiveProgressTracker,
    CandidateEvaluator,
    CandidateGenerator,
    MaterializingArchiveSearch,
    canonical_expression_key,
)
from .unbound_enumerative_search import (
    UnboundEnumerativeSearch,
    build_unbound_enumerative_search,
)

__all__ = [
    "ARCHIVE_MINIMIZE",
    "DEFAULT_ACTIVE_CORRELATION_THRESHOLD",
    "DEFAULT_FIRST_PROMOTION_TOP_K",
    "DEFAULT_MAX_DEPTH",
    "DEFAULT_PROMOTION_ADD_K",
    "DEFAULT_PROMOTION_INTERVAL",
    "DEFAULT_PROMOTION_MEAN_GAIN",
    "DEFAULT_PROMOTION_MIN_GAIN",
    "DEFAULT_PROMOTION_REFRESH_TOP_N",
    "ArchiveProgressTracker",
    "BoundedExpressionEnumerator",
    "BoundedGrammarEnumerator",
    "CandidateEvaluator",
    "CandidateGenerator",
    "EnumerationResult",
    "FilteredArchiveStep",
    "FilteredHistoryArchive",
    "GPArchiveStep",
    "MaterializingArchiveSearch",
    "MaterializingGeneticProgramming",
    "UnboundEnumerativeSearch",
    "absolute_pearson_correlation",
    "build_enumerative_search",
    "build_random_search",
    "build_search_algorithm",
    "build_unbound_enumerative_search",
    "canonical_expression_key",
    "collect_evaluation_free_expressions",
    "collect_unique_expressions",
    "correlation_rejection",
    "is_correlated_pairwise",
    "iter_bounded_expressions",
    "validate_archive_quality_threshold",
    "validate_correlation_threshold",
]
