"""Structured run artifact contract.

This package defines the portable artifacts that analysis and tracking will
consume: a schema-versioned run manifest with content fingerprints, stable
expression-derived feature IDs, the run-relative artifact paths, and the
CSV/JSON schemas for inputs, candidates, generations, final archive, archive
snapshots, and status.

Loose legacy CSV/JSON outputs (for example a standalone diagnostics CSV or a
standalone archive snapshot) are never structured runs: integrity evidence
comes from content fingerprints, never from paths alone.
"""

from .artifacts import (
    ARCHIVE_SNAPSHOTS_DIRECTORY,
    CANDIDATES_COLUMNS,
    CANDIDATES_FILENAME,
    DATASET_RECORD_FILENAME,
    FINAL_ARCHIVE_FILENAME,
    FINGERPRINT_PREFIX,
    GENERATIONS_COLUMNS,
    GENERATIONS_FILENAME,
    INPUTS_DIRECTORY,
    MAPPING_RECORD_FILENAME,
    MMAP_MANIFEST_RECORD_FILENAME,
    RUN_MANIFEST_FILENAME,
    RUN_MANIFEST_FINGERPRINT_FILENAME,
    RUN_MANIFEST_FORMAT,
    RUN_MANIFEST_SCHEMA_VERSION,
    RUN_STATES,
    RUN_STATUS_FILENAME,
    STATUS_FORMAT,
    STATUS_SCHEMA_VERSION,
    archive_snapshot_path,
    build_dataset_record,
    build_mapping_record,
    build_mmap_manifest_record,
    build_run_manifest,
    build_status,
    canonical_json_text,
    feature_id,
    fingerprint_bytes,
    fingerprint_expression,
    fingerprint_file,
    fingerprint_mapping,
    fingerprint_mmap_manifest,
    fingerprint_text,
    generation_from_snapshot_path,
    load_run_manifest,
    load_status,
    read_candidates_csv,
    read_generations_csv,
    write_candidates_csv,
    write_generations_csv,
    write_run_manifest,
    write_status,
)
from .run_bundle import (
    PARTIAL_DIRECTORY,
    RUN_BUNDLE_FORMAT,
    RUN_BUNDLE_SCHEMA_VERSION,
    RunBundle,
    RunBundleError,
    RunBundleValidationError,
    RunBundleWriter,
    create_run_bundle,
    finalize_run_bundle,
    load_run_bundle,
    open_run_bundle,
    validate_run_bundle,
    write_run_bundle,
)

__all__ = [
    "ARCHIVE_SNAPSHOTS_DIRECTORY",
    "CANDIDATES_COLUMNS",
    "CANDIDATES_FILENAME",
    "DATASET_RECORD_FILENAME",
    "FINAL_ARCHIVE_FILENAME",
    "FINGERPRINT_PREFIX",
    "GENERATIONS_COLUMNS",
    "GENERATIONS_FILENAME",
    "INPUTS_DIRECTORY",
    "MAPPING_RECORD_FILENAME",
    "MMAP_MANIFEST_RECORD_FILENAME",
    "RUN_MANIFEST_FILENAME",
    "RUN_MANIFEST_FINGERPRINT_FILENAME",
    "RUN_MANIFEST_FORMAT",
    "RUN_MANIFEST_SCHEMA_VERSION",
    "RUN_STATES",
    "RUN_STATUS_FILENAME",
    "STATUS_FORMAT",
    "STATUS_SCHEMA_VERSION",
    "archive_snapshot_path",
    "build_dataset_record",
    "build_mapping_record",
    "build_mmap_manifest_record",
    "build_run_manifest",
    "build_status",
    "canonical_json_text",
    "feature_id",
    "fingerprint_bytes",
    "fingerprint_expression",
    "fingerprint_file",
    "fingerprint_mapping",
    "fingerprint_mmap_manifest",
    "fingerprint_text",
    "generation_from_snapshot_path",
    "load_run_manifest",
    "load_status",
    "read_candidates_csv",
    "read_generations_csv",
    "write_candidates_csv",
    "write_generations_csv",
    "write_run_manifest",
    "write_status",
    "PARTIAL_DIRECTORY",
    "RUN_BUNDLE_FORMAT",
    "RUN_BUNDLE_SCHEMA_VERSION",
    "RunBundle",
    "RunBundleError",
    "RunBundleValidationError",
    "RunBundleWriter",
    "create_run_bundle",
    "finalize_run_bundle",
    "load_run_bundle",
    "open_run_bundle",
    "validate_run_bundle",
    "write_run_bundle",
]
