"""Typed, immutable feature transformation definitions and numba kernels."""

from .feature_materialization import (
    CREATED_AT_COLUMN,
    FEATURE_MMAP_SUFFIX,
    MERCHANT_ID_COLUMN,
    FeatureMaterializer,
    materialize_aggregation,
    materialize_feature,
    materialize_individual,
)
from .feature_spec import (
    AMOUNT_COLUMN,
    ROW_WINDOWS,
    TIME_WINDOWS,
    TOTAL_HISTORY_WINDOW,
    WINDOW_CATALOG,
    Aggregation,
    FeatureSpec,
    RowWindow,
    TimeWindow,
    TotalHistoryWindow,
    Window,
)
from .grammar import Feature, Mean, WindowIndex, build_grammar
from .gp import (
    MaterializingGeneticProgramming,
    build_search_algorithm,
)
from .kernels import (
    COUNT,
    MAX,
    MEAN,
    ROW_WINDOW,
    SUM,
    TIME_WINDOW,
    TOTAL_HISTORY,
    aggregate,
    sliding_window,
)

__all__ = [
    "AMOUNT_COLUMN",
    "COUNT",
    "CREATED_AT_COLUMN",
    "FEATURE_MMAP_SUFFIX",
    "MAX",
    "MEAN",
    "MERCHANT_ID_COLUMN",
    "ROW_WINDOW",
    "ROW_WINDOWS",
    "SUM",
    "TIME_WINDOW",
    "TIME_WINDOWS",
    "TOTAL_HISTORY",
    "TOTAL_HISTORY_WINDOW",
    "WINDOW_CATALOG",
    "Aggregation",
    "Feature",
    "FeatureMaterializer",
    "FeatureSpec",
    "MaterializingGeneticProgramming",
    "Mean",
    "RowWindow",
    "TimeWindow",
    "TotalHistoryWindow",
    "Window",
    "WindowIndex",
    "aggregate",
    "build_grammar",
    "build_search_algorithm",
    "materialize_aggregation",
    "materialize_feature",
    "materialize_individual",
    "sliding_window",
]
