"""Reusable dataset sorting, validation, and encoding functions."""

from .encoding import (
    CATEGORICAL_COLUMNS,
    DEFAULT_MAPPING_OUTPUT,
    encode_transactions,
    fit_label_mapping,
    load_label_mapping,
)
from .features.archive import (
    ARCHIVE_PROXY_OBJECTIVES,
    DEFAULT_ARCHIVE_CORRELATION_THRESHOLD,
    DEFAULT_ARCHIVE_QUALITY_THRESHOLD,
    ArchiveSnapshot,
    ArchiveStep,
    FilteredArchiveStep,
    FilteredHistoryArchive,
    GPArchiveStep,
    absolute_pearson_correlation,
    correlation_rejection,
    is_correlated_pairwise,
    load_archive,
    validate_archive_quality_threshold,
    validate_correlation_threshold,
)
from .features.feature_materialization import (
    FeatureMaterializer,
    materialize_aggregation,
    materialize_feature,
    materialize_individual,
)
from .features.runner import (
    DIAGNOSTIC_COLUMNS,
    RunnerDiagnosticsRecorder,
    SearchRunResult,
    SearchStrategy,
    run_feature_search,
    write_summary_json,
)
from .fitness import (
    FitnessEvaluator,
    NumericalFitnessError,
    RandomForestFitness,
    ResidualEvaluator,
    ResidualFitness,
)
from .preprocessing import preprocess
from .sorting import (
    DEFAULT_CARD_TOKENS_INPUT,
    DEFAULT_DATASET_INPUT,
    DEFAULT_DATASET_OUTPUT,
    DEFAULT_INPUT,
    DEFAULT_MERCHANTS_INPUT,
    DEFAULT_OUTPUT,
    DUCKDB_MEMORY_LIMIT,
    PROJECT_ROOT,
    sort_dataset,
    sort_transactions,
)
from .transaction_materialization import (
    DEFAULT_MMAP_DIR,
    column_dtype,
    load_mmapped_columns,
    materialize_transactions,
    read_manifest,
)
from .validation import first_sorting_violation

__all__ = [
    "ARCHIVE_PROXY_OBJECTIVES",
    "CATEGORICAL_COLUMNS",
    "DEFAULT_ARCHIVE_CORRELATION_THRESHOLD",
    "DEFAULT_ARCHIVE_QUALITY_THRESHOLD",
    "DEFAULT_CARD_TOKENS_INPUT",
    "DEFAULT_DATASET_INPUT",
    "DEFAULT_DATASET_OUTPUT",
    "DEFAULT_INPUT",
    "DEFAULT_MAPPING_OUTPUT",
    "DEFAULT_MERCHANTS_INPUT",
    "DEFAULT_MMAP_DIR",
    "DEFAULT_OUTPUT",
    "DIAGNOSTIC_COLUMNS",
    "DUCKDB_MEMORY_LIMIT",
    "PROJECT_ROOT",
    "ArchiveSnapshot",
    "ArchiveStep",
    "FeatureMaterializer",
    "FilteredArchiveStep",
    "FilteredHistoryArchive",
    "FitnessEvaluator",
    "GPArchiveStep",
    "NumericalFitnessError",
    "RandomForestFitness",
    "ResidualEvaluator",
    "ResidualFitness",
    "RunnerDiagnosticsRecorder",
    "SearchRunResult",
    "SearchStrategy",
    "absolute_pearson_correlation",
    "column_dtype",
    "correlation_rejection",
    "encode_transactions",
    "first_sorting_violation",
    "fit_label_mapping",
    "is_correlated_pairwise",
    "load_archive",
    "load_label_mapping",
    "load_mmapped_columns",
    "materialize_aggregation",
    "materialize_feature",
    "materialize_individual",
    "materialize_transactions",
    "preprocess",
    "read_manifest",
    "run_feature_search",
    "sort_dataset",
    "sort_transactions",
    "validate_archive_quality_threshold",
    "validate_correlation_threshold",
    "write_summary_json",
]
