"""Compatibility facade for the automated feature-engineering package.

The package-level exports remain stable during the namespace migration.  New
code can use ``automatedfe.data`` for the data pipeline,
``automatedfe.evaluation`` for model evaluation, ``automatedfe.search`` for
search orchestration, and ``automatedfe.cli`` for command-line adapters.
"""

from .data.encoding import (
    CATEGORICAL_COLUMNS,
    DEFAULT_MAPPING_OUTPUT,
    encode_transactions,
    fit_label_mapping,
    load_label_mapping,
)
from .search.archive import (
    ACTIVE_SET_FORMAT_IDENTIFIER,
    ACTIVE_SET_FORMAT_VERSION,
    ARCHIVE_PROXY_OBJECTIVES,
    DEFAULT_ACTIVE_CORRELATION_THRESHOLD,
    DEFAULT_ARCHIVE_CORRELATION_THRESHOLD,
    DEFAULT_ARCHIVE_QUALITY_THRESHOLD,
    DEFAULT_FIRST_PROMOTION_TOP_K,
    DEFAULT_PROMOTION_ADD_K,
    DEFAULT_PROMOTION_INTERVAL,
    DEFAULT_PROMOTION_MEAN_GAIN,
    DEFAULT_PROMOTION_MIN_GAIN,
    DEFAULT_PROMOTION_REFRESH_TOP_N,
    ActiveSetSnapshot,
    ArchiveSnapshot,
    ArchiveStep,
    ActiveSetManager,
    GPArchiveStep,
    absolute_pearson_correlation,
    correlation_rejection,
    is_correlated_pairwise,
    load_active_set_snapshot,
    load_archive,
    validate_archive_quality_threshold,
    validate_correlation_threshold,
)
from .features.feature_materialization import (
    FeatureMaterializer,
    materialize_aggregation,
    materialize_feature,
    materialize_individual,
)
from .search.runner import (
    DIAGNOSTIC_COLUMNS,
    RunnerDiagnosticsRecorder,
    SearchAnalysisError,
    SearchRunResult,
    SearchStrategy,
    run_feature_search,
)
from .search.lifecycle import SearchLifecycleRecorder
from .evaluation import (
    ActiveResidualEvaluator,
    ActiveResidualFitness,
    FitnessEvaluator,
    NumericalFitnessError,
    RandomForestFitness,
    ResidualEvaluator,
    ResidualFitness,
)
from .data.preprocessing import preprocess
from .data.sorting import (
    DEFAULT_CARD_TOKENS_INPUT,
    DEFAULT_DATASET_INPUT,
    DEFAULT_DATASET_OUTPUT,
    DEFAULT_INPUT,
    DEFAULT_MERCHANTS_INPUT,
    DEFAULT_OUTPUT,
    DUCKDB_MEMORY_LIMIT,
    PROJECT_ROOT,
    sort_dataset,
    sort_transactions,
)
from .data.transaction_materialization import (
    DEFAULT_MMAP_DIR,
    column_dtype,
    load_mmapped_columns,
    materialize_transactions,
    read_manifest,
)
from .data.validation import first_sorting_violation

__all__ = [
    "ACTIVE_SET_FORMAT_IDENTIFIER",
    "ACTIVE_SET_FORMAT_VERSION",
    "ARCHIVE_PROXY_OBJECTIVES",
    "DEFAULT_ACTIVE_CORRELATION_THRESHOLD",
    "CATEGORICAL_COLUMNS",
    "DEFAULT_ARCHIVE_CORRELATION_THRESHOLD",
    "DEFAULT_ARCHIVE_QUALITY_THRESHOLD",
    "DEFAULT_FIRST_PROMOTION_TOP_K",
    "DEFAULT_PROMOTION_ADD_K",
    "DEFAULT_PROMOTION_INTERVAL",
    "DEFAULT_PROMOTION_MEAN_GAIN",
    "DEFAULT_PROMOTION_MIN_GAIN",
    "DEFAULT_PROMOTION_REFRESH_TOP_N",
    "DEFAULT_CARD_TOKENS_INPUT",
    "DEFAULT_DATASET_INPUT",
    "DEFAULT_DATASET_OUTPUT",
    "DEFAULT_INPUT",
    "DEFAULT_MAPPING_OUTPUT",
    "DEFAULT_MERCHANTS_INPUT",
    "DEFAULT_MMAP_DIR",
    "DEFAULT_OUTPUT",
    "DIAGNOSTIC_COLUMNS",
    "DUCKDB_MEMORY_LIMIT",
    "PROJECT_ROOT",
    "ArchiveSnapshot",
    "ArchiveStep",
    "ActiveSetManager",
    "ActiveSetSnapshot",
    "ActiveResidualEvaluator",
    "ActiveResidualFitness",
    "FeatureMaterializer",
    "FitnessEvaluator",
    "GPArchiveStep",
    "NumericalFitnessError",
    "RandomForestFitness",
    "ResidualEvaluator",
    "ResidualFitness",
    "RunnerDiagnosticsRecorder",
    "SearchAnalysisError",
    "SearchLifecycleRecorder",
    "SearchRunResult",
    "SearchStrategy",
    "absolute_pearson_correlation",
    "column_dtype",
    "correlation_rejection",
    "encode_transactions",
    "first_sorting_violation",
    "fit_label_mapping",
    "is_correlated_pairwise",
    "load_active_set_snapshot",
    "load_archive",
    "load_label_mapping",
    "load_mmapped_columns",
    "materialize_aggregation",
    "materialize_feature",
    "materialize_individual",
    "materialize_transactions",
    "preprocess",
    "read_manifest",
    "run_feature_search",
    "sort_dataset",
    "sort_transactions",
    "validate_archive_quality_threshold",
    "validate_correlation_threshold",
]
