"""Run the full preprocessing pipeline.

Sorts the event dataset, sorts and enriches transactions, fits the label
mapping on the training split, and label-encodes the transformed transactions
in place.
"""

from __future__ import annotations

from pathlib import Path

from .encoding import (
    DEFAULT_MAPPING_OUTPUT,
    encode_transactions,
    fit_label_mapping,
)
from .materialization import (
    DEFAULT_MMAP_DIR,
    materialize_transactions,
)
from .sorting import (
    DEFAULT_CARD_TOKENS_INPUT,
    DEFAULT_DATASET_INPUT,
    DEFAULT_DATASET_OUTPUT,
    DEFAULT_INPUT,
    DEFAULT_MERCHANTS_INPUT,
    DEFAULT_OUTPUT,
    sort_dataset,
    sort_transactions,
)


def preprocess(
    transactions_path: Path = DEFAULT_INPUT,
    transformed_path: Path = DEFAULT_OUTPUT,
    *,
    card_tokens_path: Path | None = DEFAULT_CARD_TOKENS_INPUT,
    merchants_path: Path | None = DEFAULT_MERCHANTS_INPUT,
    dataset_path: Path = DEFAULT_DATASET_INPUT,
    dataset_output_path: Path = DEFAULT_DATASET_OUTPUT,
    mapping_path: Path = DEFAULT_MAPPING_OUTPUT,
    mmap_dir: Path = DEFAULT_MMAP_DIR,
    materialize: bool = True,
    force: bool = False,
    progress: bool = False,
) -> None:
    """Run the full preprocessing pipeline end to end.

    The two sort steps honour *force* (their outputs must not already exist
    unless it is set). ``fit`` and ``encode`` always overwrite, because their
    inputs were just regenerated by the sort steps: ``encode`` rewrites
    *transformed_path* in place. When *materialize* is true, each numeric
    column of the encoded transactions is materialized into a memory-mapped
    file under *mmap_dir* (also honouring *force*). When *progress* is true,
    the sort steps print a live DuckDB progress bar to stderr and the
    materialization step logs per-chunk progress.
    """

    sort_dataset(dataset_path, dataset_output_path, force=force, progress=progress)
    sort_transactions(
        transactions_path,
        transformed_path,
        card_tokens_path=card_tokens_path,
        merchants_path=merchants_path,
        force=force,
        progress=progress,
    )
    fit_label_mapping(transformed_path, dataset_path, mapping_path, force=True)
    encode_transactions(transformed_path, transformed_path, mapping_path, force=True)
    if materialize:
        materialize_transactions(
            transformed_path, mmap_dir, force=force, progress=progress
        )


__all__ = [
    "DEFAULT_CARD_TOKENS_INPUT",
    "DEFAULT_DATASET_INPUT",
    "DEFAULT_DATASET_OUTPUT",
    "DEFAULT_INPUT",
    "DEFAULT_MAPPING_OUTPUT",
    "DEFAULT_MERCHANTS_INPUT",
    "DEFAULT_MMAP_DIR",
    "DEFAULT_OUTPUT",
    "preprocess",
]
